name: reviewdog (code review)

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-setup@v1
      - name: Run reviewdog
        run: reviewdog -version
